services:
  spring-boot-app:
    image: backend
    ports:
      - "8091:8091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/api_etudiant
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=api_etudiant
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - api_etudiant:/var/lib/mysql

volumes:
  api_etudiant:
